testerBudLogo = "css: nav.navbar a.fw-bold"
practiveSitesDropdown = "id: practice-sites-dropdown"
practiceSitesToggleMenu = "css: div.dropdown-menu a"
webFormAutomationLink = "css: a[href='/practice-forms']"
automateWebFormText = "css: div.card-body h2"
selectCountryDropdownLocator = "css: div.card-body form > div:nth-child(1) > select"
selectTitleDropdownLocator = "css: form > div:nth-child(2) > select"
firstNameInput = "css: div.row > div:nth-child(1) > input"
lastNameInput = "css: form > div.row > div:nth-child(2) > input"
dobInput = "css: div.react-datepicker-wrapper input"
emailInput = "css: input[type='email']"
phoneNumberExtensionDropdown = "css: div.col-md-4  select"
phoneNumberInput = "css: input[type='tel']"
emailRadioButton = "css: input[value='email']"
dateOfJoiningInput = "css: div:nth-child(5) > input"
submitButton = "css: button[type='submit']"
